CREATE TABLE "GCG_5753_Invst_Summ"(
 "QUOTE" CHAR(7),
 "OP_TRAIN" LONGVARCHAR,
 "ELECTRICAL" LONGVARCHAR,
 "SHOP_AIR" LONGVARCHAR,
 "LEAD_TIME" LONGVARCHAR,
 "PAY_TERM_COM" LONGVARCHAR,
 "COMMENTS" LONGVARCHAR);
 
 CREATE INDEX "GCG_5753_Invst_Summ" ON "GCG_5753_Invst_Summ"("QUOTE");